# Generated by Django 3.2.5 on 2022-04-28 12:37

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('notes', models.TextField(blank=True, max_length=300, null=True, verbose_name='Notes')),
                ('auth_token', models.CharField(blank=True, max_length=24, null=True, primary_key=None, verbose_name='Authentication Code')),
                ('auth_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Authentication Code Expiry Date')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.TextField(max_length=300, verbose_name='Expense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('gst', models.BooleanField(verbose_name='Includes GST?')),
                ('notes', models.TextField(blank=True, max_length=600, null=True, verbose_name='Notes')),
                ('image', models.FilePathField(blank=True, null=True, path='./expenses', verbose_name='Image_File')),
                ('date_added', models.DateTimeField(verbose_name='Date Added')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='receipts.client', verbose_name='User')),
            ],
        ),
    ]
